kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - mysql-svc.yml
  - todo-svc.yml
  - todo-secrets.yml
  - db-pvc.yml
  - mysql.yml
  - todo.yml

configMapGenerator:
  - name: db-init
    files:
      - db.sql

commonAnnotations:
  project: todonodejs