apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocp-etcd-backup

commonLabels:
  app: ocp-backup

resources:
  - project.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - clusterrolebinding-scc.yaml
  - pv.yaml
  - pvc.yaml
  - cronjob.yaml
