---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache
  name: apache
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: admin
    port: 9990
    protocol: TCP
    targetPort: 9990
  selector:
    app: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
spec:
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: registry.access.redhat.com/ubi8/httpd-24:latest
        name: apache
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
