---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache
  name: apache
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: admin
    port: 9990
    protocol: TCP
    targetPort: 9990
  selector:
    app: apache
