apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: docker.io/polinux/stress:latest
    resources:
      limits:
        memory: "200Mi"
        cpu: 2000m
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
