apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: docker.io/polinux/stress-ng:latest
    resources:
      limits:
        memory: "100Mi"
        cpu: "50m"
      requests:
        memory: "100Mi"
        cpu: "50m"
    command: ["stress-ng"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1", "--cpu", "5", "--cpu-load", "100", "--aggressive"]
