apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: docker.io/polinux/stress:latest
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "50M", "--vm-hang", "0", "--cpu", "10"]
