apiVersion: v1
kind: Pod
metadata:
  labels:
    run: base
  name: base
spec:
  containers:
  - image: registry.access.redhat.com/ubi8/ubi:latest
    name: base
    command:
    - /bin/sh
    args:
    - -c
    - while true; do sleep 1; echo -n 'it is now '; date ; done
