apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-block-ec
  namespace: demo-fail
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-storagecluster-ceph-rbd-block-ec
